FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY app ./app
COPY public ./public
COPY worker ./worker
COPY next.config.ts vite.config.ts postcss.config.mjs tsconfig.json ./
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
